### ISSUE TITLE
Nested command in the same test

### ISSUE THREAD

**Issue by 3fr61n** [Juniper/jsnapy#131]
Hi

I would like to know if there is any way for (of plan to include) nested commands, or nested test, in the way that output from the parent command will help the child command to validate information.

Something like...   I would like to see that 'all isis interfaces has also mpls enabled', so I first need to get the list of isis interfaces, then for each one, check if their mpls state.

Not sure if the best way to define the test would be ...

  ```
check_mpls_on_isis_interfaces:
  - command: show isis interface 
  - iterate:
      xpath: //isis-interface
      id: './interface-name'
      execute:
        - command: show isis interface
        - item:
            xpath: //mpls-interface[interface-name = "{{ id }}"]
            tests:
              - is-equal: mpls-interface-state, Up      
```

Thanks in advance
Efrain
