### ISSUE TITLE
snapcheck support for stored snapshots

### ISSUE THREAD

**Issue by astiphout** [Juniper/jsnapy#132]
snapcheck supports checking predefined criteria against current configuration of each device.
Request is to add support for checking predefined criteria against existing stored snapshots; such a feature would prevent retrieving an extra snapshot when the necessary information has already been retrieved as part of regular snapshot retrieval (for --check). Possibly for consistency:
. use --snapcheck for diff only
. add keywork e.g. --verify, for predefined check either against local snapshot or live network

**Comment by eeishaan** [comment]
@astiphout Say the snapshot was created using the following command

`jsnapy --snap PRE -f config_check.yml`

Path 1:
We use a command line parameter say '--local' to specify the name of the snapshot on which we intend to run tests
eg : `jsnapy --snapcheck -f config_check.yml --local PRE`


Path 2:
We introduce a new section named 'local' in config_check.yml and then specify various snapshots on which we want to run the tests
eg:

```
hosts:
  - device: 10.209.16.204
    username: demo 
    passwd: demo123
tests:
  - test_diff.yml 
local:
  - PRE
  - PRE_08082016
  - POST_09082016
```
Of course, the hosts section would them be ignored in the presence of 'local'.

Which pathway would be more convenient to the user ? Kindly provide some feedback.
