### ISSUE TITLE
Unable to define multiple devices in the config file

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#138]
Hi 

I tried to configure multiple devices in the test file, but only the first device on the list get executed. Did I missed something ?

```yaml
hosts:
  - device: 127.0.0.1
    username : root
    passwd: Juniper
    port: 2222
  - device: 127.0.0.1
    username : root
    passwd: Juniper
    port: 2200

tests:
  - test_junos_interface.yml
```
