### ISSUE TITLE
got error if the xpath return nothing

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#139]
Hi 

I noticed that currently jsnapy raise an error if the Xpath return nothing. 
It's an issue for Xpath that are tracking error messages for example. 
We want to check for error but it the XPAth return nothing, it mean there is no error.

In the SLAX version, this Xpath was valid, it was just returning a list of 0 member
 
Maybe we should allow a Xpath to return an empty list and add an option to define the minimum numbers of elements an XPATH should return.
I can see many cases where it would be handy.
·         Check there are 2 RE
·         Check there are 4 Uplinks etc ..
 
```
Tests Included: check_alarm
************************ Command: show chassis alarms ************************
ERROR!! Nodes are not present in given Xpath: <//alarm-detail>
FAIL | "alarm-class" is in list ['Major', 'Warning'] [ 0 matched / 1 failed ]
```

Thanks
Damien

**Comment by maxdevyatov** [comment]
This will be helpful for many tests.
I believe this should be True:
SOME_SNAPSHOT list-not-less EMPTY_SNAPSHOT
EMPTY_SNAPSHOT list-not-more SOME_SNAPSHOT
EMPTY_SNAPSHOT no-diff EMPTY_SNAPSHOT
EMPTY_SNAPSHOT same EMPTY_SNAPSHOT
SOMETHING not-exist EMPTY_SNAPSHOT
SOMETHING not-in EMPTY_SNAPSHOT
and some others.

**Comment by eeishaan** [comment]
The rational behind the current behaviour:
Let's say I run the following test:
```
test_fpc_version:
  - command: show chassis hardware clei-models
  - iterate:
      xpath: ./chassis/chassis-module
      id: name
      tests:
        - no-diff: chassis-sub-module/version
```
Now there are two xpaths to consider here:

1. The one mentioned in 'xpath' 
2. The one mentioned after 'no-diff'

This is how the program works now:

1. Extract elements that match the first given xpath.
2. If nothing is found, then an error is raised because there is nothing that can be done on  missing nodes.
3. If something is found, then it tries to find the second xpath given.
4. After searching for second xpath, happens something in the code that is operator dependent. If nothing is found in this second search, some operators (eg no-diff) treat it as null and continue with their work, while some complain and raise an error.


The program treats the absence of nodes for a given xpath as error because:

1. One must have expected some nodes to be there and thus wrote the tests in the first place. If not found the program should notify the user about the same.
2. No operations can be performed on a missing node. Either we can skip the test altogether or fail it. Passing it (however necessary it may seem) just doesn't feel right.   

What I propose:

Keeping in mind that there is demand for old behaviour, two solutions have been drawn up

1. Introduction of a new optional attribute : ignore-null.
    This can be used with every operator and brings back the old behaviour of passing the test in the absence of nodes for which xpath ( either of the above mentioned two ) is provided. One thing to note is that instead of classifying this as Error in the absence of nodes, the program would now just SKIP the test, not pass, just skip.
So the above test now becomes:
```
   test_fpc_version:
  - command: show chassis hardware clei-models
  - iterate:
      xpath: ./chassis/chassis-module
      id: name
      tests:
        - no-diff: chassis-sub-module/version
           ignore-null: true
```

2. Use conditional test operators : #46 in the upcoming 1.1 version.
If one wants the old behaviour of PASSING the test in the absence of nodes, one can do the following:

```
test_fpc_version:
  - command: show chassis hardware clei-models
  - iterate:
      xpath: ./chassis/chassis-module
      id: name
      tests:
        OR:
                  - not-exists: ./chassis/chassis-module/chassis-sub-module/version
                  - no-diff: chassis-sub-module/version
```

In this, if the nodes along the xpath : `./chassis/chassis-module/chassis-sub-module/version` are absent then the `no-exists` test would evaluate to true and skip the next operator. This way the whole test evaluates to True.
If nodes are present, it works normally.


I think we all are expecting too much from each operator. It would be better to intuitively divide the work between different operators and eliminate hidden behaviors. This way it becomes easier and less frustrating for new users to pick up the tool.

Request you to kindly comment.

**Comment by maxdevyatov** [comment]
@eeishaan 

I believe first example should work fine with the old JSNAP behavior too. If something has changed there is no Xpath or Xpath item changed, test should fail.
Proposed functionality should add this: if you didn't have some Xpath before and don't have it now then no-diff should pass.

Some use cases we cannot do right now with JSNAPy:
1) Check that the number of OSPF/LDP neighbors not decreased.
It will fail now if there was no any any neighbors at all.
2) Check and display alarms.
To check them you need to verify Xpath alarm-detail and fail and display it when it's there.
But when you don't have alarms your test will fail due to absence of such Xpath.

**Comment by vnitinv** [comment]
@maxdevyatov "if you didn't have some Xpath before and don't have it now then no-diff should pass."

It work for me.
ex:

```
cat test_no_diff_fpc.yml
test_fpc_version:
  - command: show chassis hardware clei-models
  - iterate:
      xpath: ./chassis/chassis-module
      id: name
      tests:
        - no-diff: chassis-sub-module/version
```

$ jsnapy --check pre post -f nitin.yml -v
**************************** Device: choc-mx240-k ****************************
Tests Included: test_fpc_version 
***************** Command: show chassis hardware clei-models *****************
----------------------Performing no-diff Test Operation----------------------
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < ['REV 30'] > now it is < ['REV 30'] > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < ['REV 30', 'REV 30'] > now it is < ['REV 30', 'REV 30'] > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
Test PASSED: chassis-sub-module/version before was < None > now it is < None > 
PASS | All "chassis-sub-module/version" is same in pre and post snapshot [ 10 matched ]

With a config of:
```
> show chassis hardware clei-models 
Hardware inventory:
Item             Version  Part number  CLEI code         FRU model number
Midplane         REV 07   xxxxxxxxxxxx                     xxxxxxxxxxxx
FPM Board        REV 05   xxxxxxxxxxxx                   xxxxxxxxxxxx
PEM 0            Rev 05   xxxxxxxxxxxx                    xxxxxxxxxxxx
PEM 2            Rev 05   xxxxxxxxxxxx                     xxxxxxxxxxxx
Routing Engine 0 REV 18   xxxxxxxxxxxx                     xxxxxxxxxxxx
CB 0             REV 17   xxxxxxxxxxxx                       xxxxxxxxxxxx
CB 1             REV 17   xxxxxxxxxxxx                       xxxxxxxxxxxx
FPC 1            REV 31   xxxxxxxxxxxx   xxxxxxxxxxxx      xxxxxxxxxxxx
  MIC 0          REV 30   xxxxxxxxxxxx7   xxxxxxxxxxxx       xxxxxxxxxxxx
  MIC 1          REV 30   xxxxxxxxxxxx2   xxxxxxxxxxxx       xxxxxxxxxxxx
FPC 2            REV 31   xxxxxxxxxxxx   xxxxxxxxxxxx       xxxxxxxxxxxx
  MIC 0          REV 30   xxxxxxxxxxxx  xxxxxxxxxxxx       xxxxxxxxxxxx
Fan Tray 0       REV 01   xxxxxxxxxxxx                     xxxxxxxxxxxx
