### ISSUE TITLE
Log Info and log Err, not returned by python modules

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#151]
Hi 

i noticed that the python module does not return all information from the configuration file. Especially both `info` and `err` variables are missing.
it means that is no easy way to reconstruct a meaningful and customized log messages when using the python modules.  
See test file and python module output below.   

It would be great to have the **raw** `info` and `err` returned as well 

Here is my test file 

``` yaml
test_rpc_bgp:
  - command: show bgp summary
  - iterate:
      xpath: //bgp-information/bgp-peer
      tests:
        - is-equal: peer-state, Established
          info: BGP peer {{post['peer-address']}} ({{post['peer-as']}}) is in Established State
          err:  BGP Peer {{post['peer-address']}} ({{post['peer-as']}}) is in {{post['peer-state']}} state

  - iterate:
      xpath: //bgp-information/bgp-peer[normalize-space(peer-state)='Established']
      tests:
        - is-gt: elapsed-time/@seconds, 600
          err:  BGP peer {{ post['peer-address']}} has an uptime of {{ post['elapsed-time/@seconds']}"
          info: BGP peer {{ post['peer-address']}} is UP and Established
```

``` json
"test_results": {   
  "show bgp summary": [   
      { "count": {   "fail": 2, "pass": 2},
        "expected_node_value": "Established",
        "failed": [   {   "actual_node_value": "Active",
                          "id": {   },
                          "post": {   "peer-address": "100.0.0.12",
                                       "peer-as": "65200",
                                       "peer-state": "Active"},
                          "pre": {   "peer-state": "Active"}},
                      {   "actual_node_value": "Idle",
                          "id": {   },
                          "post": {   "peer-address": "192.168.0.2",
                                       "peer-as": "60012",
                                       "peer-state": "Idle"},
                          "pre": {   "peer-state": "Idle"}}
                  ],
        "node_name": "peer-state",
        "passed": [   {   "actual_node_value": "Established",
                          "id": {   },
                          "post": {   "peer-address": "100.0.0.11",
                                       "peer-as": "65200",
                                       "peer-state": "Established"},
                          "pre": {   "peer-state": "Established"}},
                      {   "actual_node_value": "Established",
                          "id": {   },
                          "post": {   "peer-address": "192.168.0.0",
                                       "peer-as": "60011",
                                       "peer-state": "Established"},
                          "pre": {   "peer-state": "Established"}}],
          "result": False,
          "testoperation": "is-equal",
          "xpath": "//bgp-information/bgp-peer"
      }
```
