### ISSUE TITLE
Unable to store snapshot data in db when using names with '-' in them

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#158]
There seems to be some issue with code responsible for storing and creating database. 
My Config file looks like this:

```
hosts:
  -  device: one-plus-3
     username: xxx
     passwd: xxx
tests:
        - test_is_equal.yml
        - test_is_in.yml
        - test_get_config.yml
sqlite:
  - store_in_sqlite: yes
    check_from_sqlite: yes
    database_name: jbb.db
    compare: 2,3
```
Notice the presence of char '-' in name. 
When running with this file I get the following error:

`OperationalError: near "-": syntax error`

This issue can be traced back to the absence of double quotes around table name.
