### ISSUE TITLE
question: lldp

### ISSUE THREAD

**Issue by jedelman8** [Juniper/jsnapy#167]
I'm finding it very hard to get started.  Are there any examples to test for the following:

* Ensure the quantity of neighbors are the same pre and post change
* Verify each neighbor found should be there - so fxp0 should have 3 neighbors and they should be r1, r3, r5, ge-0/0/01 should have 1 neighbor, i.e. r1, etc.

Any help or improvement with the docs would be greaet.

**Comment by vnitinv** [comment]
@jedelman8 For your first query, we can do

```yaml
check_lldp:
- command: show lldp neighbors
- iterate:
     xpath: //lldp-neighbors-information/lldp-neighbor-information
     id: lldp-local-port-id
     tests:
       - list-not-less: lldp-local-port-id
         err: "Test FAILED!! The post snapshot has less LLDP neighbors
than the pre snapshot"
         info: "Test SUCCEEDED!! The pre and post snapshots have the
same number of LLDP neighbors"
       - list-not-more: lldp-local-port-id
         err: "Test FAILED!! The post snapshot has additional LLDP
neighbors than the pre snapshot"
         info: "Test SUCCEEDED!! The pre and post snapshots have the
same number of LLDP neighbors"
```
For 2nd query, we can do this using module/script where depending on our first result, we can generate next set of test cases at run time using say jinja template and run those.
