### ISSUE TITLE
Unable to run xpath functions

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#174]
Due to improper splitting [here](https://github.com/Juniper/jsnapy/blob/master/lib/jnpr/jsnapy/check.py#L174) (in check.py) the following test case is unable to run : 

``` yaml
test_interfaces_terse:
  - command: show interfaces terse
  - iterate:
      id: ./name
      xpath: //physical-interface
      tests:
        - exists: ./name[contains(substring(.,1,3),'pfe')]
```

An error is produced which says that the xpath is invalid.
This can be reproduced by using xpath functions in the xpath specified with the operator( `exists` here )
