### ISSUE TITLE
Extension of logical operator to whole test case

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#177]
It would be nice to have the logical operators introduced in #173 extended to the top most level as well 
It would look like something like this:

```yaml
tests_include:
        -  AND:
           - test_interfaces_terse
           - OR:
                 - test_interface_1
                 - test_interface_2
```
This will help overcome the current limitation of #173 where a user is helpless if logical operation is required between tests which have different commands.
