### ISSUE TITLE
CLI bug in jsnapy

### ISSUE THREAD

**Issue by blc325** [Juniper/jsnapy#180]
When I used this specific test:

virtual_chassis_status:
  - command: show virtual-chassis status
  - iterate:
      xpath: //member
      tests:
        - is-equal: member-status, Prsnt 

, it kept having this error:
ERROR Occurred: string indices must be integers, not str

I had to convert the command to rpc like this and it started to work:

virtual_chassis_status:
  - rpc: get-virtual-chassis-information
  - iterate:
      xpath: //member
      tests:
        - is-equal: member-status, Prsnt

**Comment by eeishaan** [comment]
@blc325

Hi

It runs perfectly fine on my device:
test_xml.yml
```yaml
virtual_chassis_status:
  - command: show virtual-chassis status
  - iterate:
      xpath: //member
      tests:
        - is-in: member-status, Prsnt
          err: "Test Failed!! VC members are not all present: <{{post['member-status']}}>"
          info: "Test Passed!! VC members are all present"
```
config.yml
```yaml
hosts:
  - device: xxxx
    username: xxx
    passwd: xxx
tests:
  - test_xml.yml 
```
output:
```bash
Taking snapshot of COMMAND: show virtual-chassis status 
************************** Device: xxxx **************************
Tests Included: virtual_chassis_status 
******************** Command: show virtual-chassis status ********************
PASS | All "member-status" is in list ['Prsnt']  [ 1 matched ]
------------------------------- Final Result!! -------------------------------
Total No of tests passed: 1
Total No of tests failed: 0 
Overall Tests passed!!! 
```

I request you to kindly check the indentation in the test file as that is know to cause expected error
