### ISSUE TITLE
Ignore-null doesn't handle `id` xpath

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#184]
For cases like this:

``` yaml
test_interfaces:
  - command: show interfaces terse et*
  - iterate:
      xpath: .
      id: physical-interface/name
      tests:
        - no-diff: physical-interface/oper-status
          err: "Test Failed!! oper-status  got changed, before it was <{{pre['physical-interface/oper-status']}}>, now it is <{{post['physical-interface/oper-status']}}> with name <{{id_0}}> and admin status <{{post['physical-interface/admin-status']}}>"
          info: "Test succeeded!! oper-status is same with value, before it is <{{pre['physical-interface/oper-status']}}> now it is <{{post['physical-interface/oper-status']}}> with admin status <{{post['physical-interface/admin-status']}}> "
          ignore-null: True
```

Ignore-null doesn't skip the test case when `id`'s xpath doesn't yield a node and raises an error. This needs to be fixed for --check operators only.
