### ISSUE TITLE
Position dependent test file

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#187]
If I run the following test:
```yaml
check_test:
  - iterate:
      tests:
        - err: 'Test Failed!! memory heap utilisation of the FPCs is not in range of 5-40, it is <{{post["memory-heap-utilization"]}}> with temperature: <{{post["temperature"]}}>'
          in-range: 'memory-heap-utilization, 5, 40'
          info: 'Test Succeeded!! memory heap utilisation of the FPCs is within the range of 5-40, it is <{{post["memory-heap-utilization"]}}> with temperature: <{{post["temperature"]}}>'
      xpath: 'fpc[normalize-space(slot) = "0"]'
  - command: show chassis fpc 
```
The following error is produced:
```bash
Connecting to device xxxx ................
ERROR!!! Test case: 'check_test' not defined properly
*************************** Device: 10.221.130.68 ***************************
Tests Included: check_test 
ERROR occurred, test keys 'command' or 'rpc' not defined properly
------------------------------- Final Result!! -------------------------------
Total No of tests passed: 0
Total No of tests failed: 0 
None of the test cases executed !!! 
```

Shifting the line `  - command: show chassis fpc ` on the top of the test case as follows works fine:
```yaml
check_test:
  - command: show chassis fpc                          
  - iterate:
      tests:
        - err: 'Test Failed!! memory heap utilisation of the FPCs is not in range of 5-40, it is <{{post["memory-heap-utilization"]}}> with temperature: <{{post["temperature"]}}>'
          in-range: 'memory-heap-utilization, 5, 40'
          info: 'Test Succeeded!! memory heap utilisation of the FPCs is within the range of 5-40, it is <{{post["memory-heap-utilization"]}}> with temperature: <{{post["temperature"]}}>'
      xpath: 'fpc[normalize-space(slot) = "0"]'
```
