### ISSUE TITLE
Buggy rpc args implementation

### ISSUE THREAD

**Issue by eeishaan** [Juniper/jsnapy#194]
When the following test case is fed:
```yaml
test_routing_engine:
  - rpc: get-interface-information
  - args:
        media: True
        interface-name: 'ge-0/0/0'

  - item:
      id: ./name
      xpath: '//physical-interface'
      tests:
        - is-equal: admin-status, down
```
the snapshot contains information for all the interfaces.

whereas feeding this test case:
```yaml
test_routing_engine:
  - rpc: get-interface-information
  - kwargs:
        media: True
        interface-name: 'ge-0/0/0'
  - item:
      id: ./name
      xpath: '//physical-interface'
      tests:
        - is-equal: admin-status, down
```

works as expected. So instead of specified `args` one needs to specify `kwargs`. This is a minor  bug which needs to be corrected.
