### ISSUE TITLE
Include description field for tests

### ISSUE THREAD

**Issue by Mierdin** [Juniper/jsnapy#309]
Would be nice if tests contained a "description" field that presented itself at runtime, kind of like how Ansible plays and tasks can be named and those human-readable names take the place of the commands actually being run. Would help make it clearer what's being tested.

**Comment by sidhujasminder** [comment]
@Mierdin like as of now if we see, for the following testcase:
```
test_rpc_get_interfaces_information:          <<<<<<---- This is the current Description we have which is like ansible task name
  - iterate:
      xpath: physical-interface
      id: name
      tests:
         - no-diff: oper-status
           info: "Passed"
           err: "Failed"
  - kwargs:
      interface-name: lo0
  - rpc: get-interface-information
```

Can you just help me figure out where we can have the description field?

**Comment by Mierdin** [comment]
Test names are not the same thing as a test description, IMO. Think of it this way - each Python unit test function requires some kind of name, but this doesn't mean you shouldn't also write a docstring for that test to provide more context.

I'm not a huge fan of the current layout of the test - namely, that the value underneath each test key is a list - I feel like using another object/dictionary would be best. However, that's probably a lot more work to retrofit, assuming you agree. So, for the meantime, this kind of UX will suffice:

```yaml
test_rpc_get_interfaces_information:
  - description: |
      This test retrieves a list of interfaces via RPC, and ensures each hasn't changed
      status from the previous snapshot
  - iterate:
      xpath: physical-interface
      id: name
      tests:
         - no-diff: oper-status
           info: "Passed"
           err: "Failed"
  - kwargs:
      interface-name: lo0
  - rpc: get-interface-information
```
