### ISSUE TITLE
show chassis alarm : issue

### ISSUE THREAD

**Issue by door7302** [Juniper/jsnapy#324]
### Description of Issue/Question

I experienced an issue to track changes (new alarm, alarm was cleared...) of show chassis alarms between pre and post snapshot. 
My jsnapy test template below works as expected when in I still have at least one alarm in pre and post snap. If in the pre snap or post snap there is no more alarm then there is an error : due to missing XPATH. 

How to accomplish a simple check of chassis alarms ? 

### Setup
```yaml
tests_include:
  - chassis_alarms

chassis_alarms:
  - command: show chassis alarms
  - iterate:
      xpath: alarm-detail
      id: alarm-description
      tests:
        - list-not-less: alarm-short-description
          ignore-null: True
          err: "This alarm has disappeared {{pre['alarm-description']}}"
        - list-not-more: alarm-short-description
          ignore-null: True
          err: "A new alarm is present {{post['alarm-description']}}"
```
### Steps to Reproduce Issue
jsnapy --snap pre -f config.yml -v

cat /root/jsnapy/snapshots/myrouter_pre_show_chassis_alarms.xml
```xml
<alarm-information>
<alarm-summary>
<no-active-alarms/>
</alarm-summary>
</alarm-information>
```
jsnapy --snap post -f config.yml -v
cat /root/jsnapy/snapshots/myrouter_post_show_chassis_alarms.xml
```xml
<alarm-information>
<alarm-summary>
<active-alarm-count>1</active-alarm-count>
</alarm-summary>
<alarm-detail>
<alarm-time seconds="1532001817">
2018-07-19 14:03:37 CEST
</alarm-time>
<alarm-class>Minor</alarm-class>
<alarm-description>Plane 0 not online</alarm-description>
<alarm-short-description>Plane 0 not online</alarm-short-description>
<alarm-type>Chassis</alarm-type>
</alarm-detail>
</alarm-information>
```

jsnapy --check pre post -f config.yml -v
```
*************************** Device: 81.253.192.16 ***************************
Tests Included: chassis_alarms
************************ Command: show chassis alarms ************************
-------------------Performing list-not-less Test Operation-------------------
SKIPPING!! Nodes are not present in given Xpath: <alarm-detail>
-------------------Performing list-not-more Test Operation-------------------
SKIPPING!! Nodes are not present in given Xpath: <alarm-detail>
------------------------------- Final Result!! -------------------------------
chassis_alarms : Skipped
Total No of tests passed: 0
Total No of tests failed: 0
None of the test cases executed !!!
```
### Versions Report
JSNAPy version: 1.3.1
