### ISSUE TITLE
Assigning wrong snap id, if same command is run multiple times in single execution 

### ISSUE THREAD

**Issue by Jainpriyal** [Juniper/jsnapy#39]
config.yml file: 

```
    hosts:
        - devices: abc
          username : pqr
           passwd: 123
     tests:
        - test_is_equal.yml
        - test_is_in.yml
        - test_get_config.yml
    sqlite:
        - store_in_sqlite: yes
          check_from_sqlite: yes 
          database_name: jbb.db
          compare: 2,3
```

test_is_equal.yml

```
            test_interfaces_terse:
              - command: show interfaces terse lo* 
              - item:
                id: ./name
                xpath: //physical-interface[normalize-space(name) = "lo0"]
                tests:
                    - is-equal: admin-status, down
                      info: Passed
                      err: Failed
```

test_is_in.yml

```
                 check_show_interfaces_terse:
                  - command: show interfaces terse lo*
                  - iterate:
                    xpath: //physical-interface[normalize-space(name) = "lo0"]
                    tests:
                       - is-in: oper-status, downoo, up
                         info: Passed
                         err: Failed
```

test_get_config: 

```
            test_rpc_version:
               - rpc: get-config
               - args:
                    filter_xml: configuration/system/login
               - item:
                    xpath: //configuration
                    tests:
                        - is-equal: //minimum-time, 60
                          info: "Test Succeeded!!"
                          err: "Test Failed!!!"

            test_interface:
                 - rpc: get-interface-information
                 - args:
                        interface-name: em0
                        media: True
                        detail: True
                - item:
                      xpath: //physical-interface
                      tests:
                         - is-gt: snmp-index, 2
                           info: "Test Succeeded!!"
                           err: "Test Failed!!"
```

When taking snapshot for above config file, it is assigning snap id number wrongly. For one execution of command it is assigning different id number. It should either overwrite or assign same id with some extra tag.

![screen shot 2016-02-16 at 5 06 31 pm](https://cloud.githubusercontent.com/assets/6584056/13075582/52fb0820-d4d2-11e5-99d5-d8ba6e1ad2f4.png)
