### ISSUE TITLE
format of config file for js.check js.snap modules ?

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#79]
Hi 

I'm trying to create a module jsnapy for ansible and I'm facing an issue
I'm following this doc : https://github.com/Juniper/jsnapy/wiki/4.-Module

I prefer to initiate the ssh connection outside of Jsnapy and pass the object to the module. 
Also I called `js.snap` and `js.check` independently. 

Snap is not reporting an error but I do not see where is the snapshot being save locally
And I get an error regarding the syntax of the configuration file for `js.check`

```
"Exception during check - ('config file not defined properly', AttributeError(\"'str' object has no attribute 'get'\",))"
```

Please do you have an example of configuration file for `js.snap` & `js.check` when the device object is provided and when we don't want to use the database.

I looked here https://github.com/Juniper/jsnapy/tree/master/lib/jnpr/jsnapy/samples but all config_\* file include hosts information which doesn't apply in my case.

Here is my code

``` python
        js = SnapAdmin()
        config_file = '/Users/dgarros/projects/lab-evpn-vxlan/jsnap_tests/mytest.yml'

        try:
            js.snap(config_file, "mytestforjsnap", dev=dev)
        except Exception as err:
            msg = 'Unable to get snap from device - {0}'.format(str(err))
            [..]

        try:
            snapvalue = js.check(config_file, "mytestforjsnap")
        except Exception as err:
            msg = 'Exception during check - {0}'.format(str(err))
            [..]
```

Below my configuration file and my test file

``` yaml
# /Users/dgarros/projects/lab-evpn-vxlan/jsnap_tests/mytest.yml
tests:
  - test_exists.yml
```

``` yaml
# /Users/dgarros/projects/lab-evpn-vxlan/jsnap_tests/test_exists.yml
tests_include:
  - test_version_check

test_version_check:
  - command: show version
  - iterate:
      id: host-name
      xpath: //software-information
      tests:
        - exists: //package-information/name
          info: "Test Succeeded!! node //package-information/name exists with name <{{pre['//package-information/name']}}> and hostname: <{{id_0}} > "
          err: "Test Failed!!! node //package-information/name does not exists in  hostname: <{{id_0}}> !! "
```
