### ISSUE TITLE
space not allowed before/after variables

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#85]
Hi 

I noticed that variables in err/info messages are not working if they have some spaces before or after.

Right not his test file do not report any error but do not print interface name neither, it just print blank

``` yaml
check_int_ext:
    - command: show interfaces extensive
    - iterate:
        xpath: //interface-information/physical-interface[normalize-space(admin-status)='up' and logical-interface/address-family/address-family-name ]
        tests:
          - is-equal: oper-status, up
            info: "Interface {{ post['name'] }} with Admin UP and Family defined are UP"
            err: Interface {{ post['name'] }} is not UP UP
```

```
Connecting to device 10.92.71.88 ................
Taking snapshot for show interfaces extensive ................
*************************Performing test on Device: 10.92.71.88*************************
Tests Included: check_int_ext
*************************Command is show interfaces extensive*************************
----------------------Performing is-equal Test Operation----------------------
Interface  is not UP UP
Interface  is not UP UP
Interface  is not UP UP
Interface  is not UP UP
```

If I remove spaces between the variable name and {{}} it's working file 

```
          - is-equal: oper-status, up
            info: "Interface {{post['name']}} with Admin UP and Family defined are UP"
            err: Interface {{post['name']}} is not UP UP
```

Ideally I think we should support spaces.  
if we don't support it, it will be great to detect it and have an error message.

Thanks
Damien
