### ISSUE TITLE
How to access an XML attribute with XPath ?

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#86]
Hi 

I would like to use the value of an XML attribute within my xpath expression as well as my test
But I'm struggling to find the right syntax
Please could you take a look and see i you have an idea. 

I tried 
- interface-flapped/@seconds
- interface-flapped[@seconds]
- interface-flapped[seconds]

But so far nothing works
Any idea would be appreciated
Thanks
Damien

``` yaml
check_int_ext:
    - command: show interfaces extensive
    - iterate:
        xpath: //interface-information/physical-interface[normalize-space(admin-status)="up" and logical-interface/address-family/address-family-name and interface-flapped[@seconds]]
        tests:
          - is-gt: interface-flapped[@seconds], 600
            info: Interfaces {{post['name']}} with family defined is UP for more than 10 min
            err: Interface {{post['name']}} is Up since XX seconds
```

See XML (simplified) below

`````` xml
    <interface-information>
        <physical-interface>
            <name>xe-0/0/0</name>
            <admin-status junos:format="Enabled">up</admin-status>
            <if-device-flags>
                <ifdf-present/>
                <ifdf-running/>
                <ifdf-down/>
            </if-device-flags>
            <ifd-specific-config-flags>
            </ifd-specific-config-flags>
            <up-hold-time>0</up-hold-time>
            <down-hold-time>0</down-hold-time>
            <current-physical-address>10:0e:7e:bd:9a:83</current-physical-address>
            <hardware-physical-address>10:0e:7e:bd:9a:83</hardware-physical-address>
            <interface-flapped junos:seconds="273055">2016-04-11 14:20:02 PDT (3d 03:50 ago)</interface-flapped>
            </logical-interface>
        </physical-interface>
    </interface-information>
```xml
``````
