### ISSUE TITLE
how to know which tests failed when using modules

### ISSUE THREAD

**Issue by dgarros** [Juniper/jsnapy#91]
Hi 

How can we know which test failed when using jsnapy module ? 
Here is the output I get when I run a test that failed with snapcheck module. 
```
Tested on 10.92.71.88
Final result:  Failed
Total passed:  0
Total failed: 1
{ 'show version invoke-on all-routing-engines': [{'actual_node_value': ['jbase',
                                                                       'junos',
                                                                       'jcrypto',
                                                                       'jdocs',
                                                                       'jkernel',
                                                                       'jpfe',
                                                                       'jroute',
                                                                       'jsdn-i386',
                                                                       'jswitch',
                                                                       'jweb-ex',
                                                                       'py-base-i386',
                                                                       'JUNOS Host Software'],
                                                 'expected_node_value': 'jbase',
                                                 'node_name': '//package-information/name[1]',
                                                 'result': False,
                                                 'testoperation': 'contains',
                                                 'xpath': '//software-information'}]}
```

There are all node value that matched but without additional information it's impossible to identify which tests failed
Also all tests are on the same list.

If will be good to have ; 
 - 1 list with all variables provided in `info` message for tests that passed
 - 1 list with all variables provided in `err` message for tests that failed

For example for this test file 
```yaml
check_alarm:
  - command: show chassis alarms
  - iterate:
      xpath: //alarm-detail
      tests:
      - not-in: alarm-class, Major, Warning
        info: Alarm  {{post['alarm-class']}} - {{post['alarm-description'] }} is good
        err:  Alarm {{post['alarm-class']}} - {{post['alarm-description'] }}
```
I would get
```
{ passed: [ 
   { alarm-class: "minor",  alarm-description: "My minor alarm"},
   { alarm-class: "minor",  alarm-description: "My other minor alarm"} 
  ]
  failed: [
   { alarm-class: "Major",  alarm-description: "My major alarm"},
   { alarm-class: "Warning",  alarm-description: "My Warning alarm"} 
   ]
}
```
